version: '3.1'

services:

  mysql-standalone:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: friends
      MYSQL_USER: test
      MYSQL_PASSWORD: example
    ports:
      - 3306:3306